<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>     
      <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.*" />
        <PackageReference Include="Aspire.Hosting.Azure.AppContainers" Version="13.*" />
        <PackageReference Include="Aspire.Hosting.Docker" Version="13.*" />        
        <PackageReference Include="GitHubActionsTestLogger" Version="3.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NUnit" Version="4.5.1" />
        <PackageReference Include="NUnit.Analyzers" Version="4.11.2" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
        <PackageReference Include="Particular.Approvals" Version="2.*" />
        <PackageReference Include="PublicApiGenerator" Version="11.5.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Particular.Aspire.Hosting.ServicePlatform\Particular.Aspire.Hosting.ServicePlatform.csproj" />
    </ItemGroup>
</Project>

